name: always_awake_flutter
description: "Always Awake Me Flutter :)"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_local_notifications: ^14.1.1
  web_socket_channel: ^2.4.0
  geolocator: ^10.1.1
  flutter_foreground_task: ^6.1.3
  sqflite: ^2.3.2
  intl: ^0.18.1

flutter:
  uses-material-design: true